#!/usr/bin/env python3.10

import sys
import subprocess
import os
import platform

BASE_DIR = os.path.dirname(os.path.abspath(__file__))

IS_WINDOWS = platform.system() == "Windows"

# Correct venv python path
if IS_WINDOWS:
    VENV_PYTHON = os.path.join("venv", "Scripts", "python.exe")
else:
    VENV_PYTHON = os.path.join("venv", "bin", "python")


def groupCmd(a, cmd):
    if len(a) >= 3:
        for i in range(2, len(a)):
            cmd[4] = a[i]
            subprocess.run(cmd)

        with open("requirements.txt", "w") as f:
            subprocess.run(
                [VENV_PYTHON, "-m", "pip", "freeze"],
                stdout=f
            )


a = sys.argv
print(a)


if len(a) > 1 and a[1] == 'i':
    groupCmd(a, [VENV_PYTHON, "-m", "pip", "install", a[2]])

elif len(a) > 1 and a[1] == 'a':
    print("Activate manually:")
    print("Windows: venv\\Scripts\\activate")
    print("Linux: source venv/bin/activ ate")
    subprocess.run(["bash", "-c", "source venv/bin/activate && exec bash"])

elif len(a) > 1 and a[1] == 'r':
    subprocess.run([VENV_PYTHON, a[2]])

elif len(a) > 1 and a[1] == 'u':
    groupCmd(a, [VENV_PYTHON, "-m", "pip", "uninstall", a[2], "-y"])

elif len(a) > 1 and a[1] == 'd':
    subprocess.run([VENV_PYTHON, "-m", "uvicorn", "api.app:app", "--reload"])

elif len(a) > 1 and a[1] == 'v':
    script_path = os.path.join(BASE_DIR, "Dl", "validimages.py")
    subprocess.run([VENV_PYTHON, script_path], check=True)

elif len(a) > 1 and a[1] == 't':
    script_path = os.path.join(BASE_DIR, "Dl", "train.py")
    subprocess.run([VENV_PYTHON, script_path], check=True)

elif len(a) > 1 and a[1] == 'm':
    script_path = os.path.join(BASE_DIR, "Dl", "main.py")
    subprocess.run([VENV_PYTHON, script_path], check=True)

elif len(a) > 1 and a[1] == 'te':
    script_path = os.path.join(BASE_DIR, "Dl", "test.py")
    subprocess.run([VENV_PYTHON, script_path], check=True)

elif len(a) > 1 and a[1] == 'setup':
    subprocess.run(["python3.10", "-m", "venv", "venv"])

else:
    print("not valid command")